name: "PAPER Lab"
description: ""
meta_description: "Paleoanthropology and Paleoecology Research Laboratory - George Washington University - W. Andrew Barr"
logo: 
favicon: ''
baseurl: ''
google_analytics: UA-30014706-6
disqus: 
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
CVlink: https://wabarr.com/assets/WAB_CV.pdf#toolbar=0&navpanes=0

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
## Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
    
permalink: :year/:month/:day/:title:output_ext/

collections:
  - people

# Pagination 
paginate: 6
paginate_path: "/blog/page:num/"
    
# Other
markdown: kramdown
highlighter: rouge